import { Metadata } from 'next'
import { FileText, Scale, Shield } from 'lucide-react'

export const metadata: Metadata = {
  title: 'GPS Hunter Terms of Service | Srapsware',
  description:
    'Read the GPS Hunter terms of service. Understand acceptable use, user responsibilities, and your rights when using the app.',
  openGraph: {
    title: 'GPS Hunter Terms of Service - Srapsware',
    description: 'Terms and conditions for using the GPS Hunter app',
    type: 'website',
  },
}

export default function GpsHunterTermsPage() {
  return (
    <main>
      <section className="relative py-16 md:py-24 border-t border-border">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto prose prose-lg dark:prose-invert">
            <div className="not-prose mb-12 grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="p-6 rounded-xl border border-border bg-card text-center">
                <FileText className="w-8 h-8 text-primary mx-auto mb-3" />
                <h3 className="font-bold mb-2">Clear Terms</h3>
                <p className="text-sm text-muted-foreground">Easy to understand</p>
              </div>
              <div className="p-6 rounded-xl border border-border bg-card text-center">
                <Scale className="w-8 h-8 text-primary mx-auto mb-3" />
                <h3 className="font-bold mb-2">Lawful Use</h3>
                <p className="text-sm text-muted-foreground">Responsible usage required</p>
              </div>
              <div className="p-6 rounded-xl border border-border bg-card text-center">
                <Shield className="w-8 h-8 text-primary mx-auto mb-3" />
                <h3 className="font-bold mb-2">Your Responsibility</h3>
                <p className="text-sm text-muted-foreground">You control how you use the app</p>
              </div>
            </div>

            <p className="text-muted-foreground not-prose mb-8">
              <strong>Last Updated:</strong> June 2026
            </p>

            <p>Welcome to GPS Hunter.</p>
            <p>
              By downloading, installing, or using GPS Hunter, you agree to these Terms of Service.
            </p>

            <h2>Purpose of the App</h2>
            <p>
              GPS Hunter is a GPS simulation and route playback tool designed for testing,
              development, educational, and other lawful purposes.
            </p>

            <h2>Acceptable Use</h2>
            <p>
              You agree to use GPS Hunter responsibly and in compliance with all applicable laws
              and regulations.
            </p>
            <p>
              You are solely responsible for how you use simulated location data generated by the
              App.
            </p>

            <h2>Prohibited Use</h2>
            <p>You agree not to use GPS Hunter:</p>
            <ul>
              <li>For unlawful activities.</li>
              <li>To violate the terms of service of third-party platforms.</li>
              <li>To commit fraud or deception.</li>
              <li>To interfere with the rights of others.</li>
            </ul>

            <h2>User Responsibility</h2>
            <p>
              You understand that GPS Hunter can simulate device location and route movement.
            </p>
            <p>
              Any consequences resulting from the use of simulated locations are your sole
              responsibility.
            </p>

            <h2>Purchases</h2>
            <p>If premium features are offered through Google Play Billing:</p>
            <ul>
              <li>Payments are processed by Google Play.</li>
              <li>Pricing may change in the future.</li>
              <li>Premium purchases unlock additional features as described in the App.</li>
            </ul>

            <h2>No Warranty</h2>
            <p>
              GPS Hunter is provided on an &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; basis.
            </p>
            <p>We make no warranties regarding:</p>
            <ul>
              <li>Accuracy</li>
              <li>Availability</li>
              <li>Reliability</li>
              <li>Fitness for a particular purpose</li>
            </ul>

            <h2>Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, SRA PSWARE shall not be liable for any
              indirect, incidental, special, consequential, or punitive damages arising from the use
              of GPS Hunter.
            </p>

            <h2>Termination</h2>
            <p>
              We reserve the right to suspend or terminate access to the App if these Terms are
              violated.
            </p>

            <h2>Changes to These Terms</h2>
            <p>
              We may update these Terms from time to time. Updated versions will be posted on this
              page.
            </p>

            <h2>Contact</h2>
            <p>For questions regarding these Terms, please contact:</p>
            <p>
              <a href="mailto:support@srapsware.com">support@srapsware.com</a>
            </p>
          </div>
        </div>
      </section>
    </main>
  )
}
