# config.yml

backend:
  name: git-gateway
  repo: shivsingh7150/srapsware-website
  branch: main
media_folder: 'assets/uploads'
collections:
    - name: 'blog'
      label: 'Blog'
      folder: '_posts/'
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      editor:
        preview: false
      fields:
        - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
        - { label: 'Title', name: 'title', widget: 'string' }
        - { label: 'Publish Date', name: 'date', widget: 'datetime' }
        - { label: 'Tags', name: 'tags', widget: 'select', multiple: true, options: ['News', 'Tech', 'Update', 'DIY', 'Downloads', 'Linux', 'How To', 'Jekyll'] }
        - { label: 'Categories', name: 'categories', widget: 'select', multiple: true, options: ['News', 'Tech', 'Update', 'DIY', 'Downloads', 'Linux', 'How To'] }
        - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          display_fields: [display_name],
          search_fields: [display_name],
          value_field: 'name',
          }
        - { label: 'Body', name: 'body', widget: 'markdown' }
        - { label: 'Post image', name: 'post_image', widget: 'image' }
      
    - name: 'authors'
      label: 'Authors'
      folder: '_authors/'
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{name}}'
      editor:
        preview: false
      fields:
        - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'author' }
        - { label: 'Short Name', name: 'name', widget: 'string' }
        - { label: 'Display Name', name: 'display_name', widget: 'string' }
        - { label: 'Position', name: 'position', widget: 'string' }
        - { label: 'Body', name: 'body', widget: 'markdown' }
    - name: 'testimonial'
      label: 'Testimonials'
      folder: '_testimonial/'
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{name}}'
      editor:
        preview: false
      fields:
        - label: 'Layout'
          name: 'layout'
          widget: 'hidden'
          default: 'testimonial'
        - label: 'Full Name'
          name: 'name'
          widget: 'string''
        - label: 'Position'
          name: 'position'
          widget: 'string'
        - label: 'Country'
          name: 'country'
          widget: 'string
        - label: 'Testimonial'
          name: 'body'
          widget: 'markdown'
  
    - name: 'portfolio'
      label: 'Portfolio'
      folder: '_portfolio/'
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      editor:
        preview: false
      fields:
        - label: 'Layout'
          name: 'layout'
          widget: 'hidden'
          default: 'portfolio'
        - label: 'Title'
          name: 'title'
          widget: 'string'
        - label: 'Projet URL'
          name: 'project_url'
          widget: 'string'
        - label: 'completed on'
          name: 'completed_on'
          widget: 'date'
        - label: 'Publish Date'
          name: 'date'
          widget: 'datetime'
        - label: 'Body'
          name: 'body'
          widget: 'markdown'
        - label: 'Featured Image'
          name: 'image'
          widget: 'image'
          allow_multiple: true
        - label: 'Categories'
          name: 'categories'
          widget: 'select'
          multiple: true
          options: ['Big Data', 'Web Design', 'Web Development', 'Mobile App', 'Server']
        - label: 'Technologies'
          name: 'technologies'
          widget: 'select'
          multiple: true
          options: ['Js', 'Php', 'Magento', 'Wordpress', 'Joomla', 'WHMCS', 'Linux', 'Windows', 'Android', 'iOS', 'Netlify', 'Jekyll', 'Next.js
', 'WooCommerce']
        - label: "Gallery"
          name: "galleryImages"
          widget: "list"
          summary: '{{fields.image}}'
          field: {label: Image, name: image, widget: image}